### ISSUE TITLE
dlh_googlemap Klasse für Datenschutz Box vergeben

### ISSUE THREAD

**Issue by theDyingMountain** [delahaye/dlh_googlemaps#105]
Es wäre sehr nützlich wenn der dlh_googlemap Container ebenfalls mit einer Klasse markiert wird, je nachdem ob er den #confirm-googlemaps Container oder die Karte enthält. Dadurch lässt sich vermeiden, dass die Bestätigungsbox bereits die Höhe der später geladenen Google Map erhält.
Möglich wären z.B. die Klassen .is-map bzw. .is-confirm

**Comment by Aybee** [comment]
Sowas in der Art wollte ich auch gerade schreiben. Mein CSS sieht jetzt so aus.
```css
.dlh_googlemap[style$="%;"] {
  padding: 0 !important;
}
#confirm-googlemaps {
  cursor: pointer;
}
```
Dies funktioniert, weil sich das inline-Style verändert, wenn die Map geladen wird.
```html
<div class="dlh_googlemap block" id="dlh_googlemap_1" style="position:relative; width:100%; padding-bottom:62.5%;">...
<div class="dlh_googlemap block" id="dlh_googlemap_1" style="position:relative; width:100%; padding-bottom:62.5%; overflow:hidden;">...
```
Besser wäre es, wenn `div.dlh_googlemap` eine Klasse "not-confirmed" vergeben würde, welche dann über die Funktion `gmap[ID]_allow()` wieder entfernt wird.

Dann könnte unser CSS so aussehen:
```css
.dlh_googlemap.not-confirmed {
  padding: 0 !important;
}
#confirm-googlemaps {
  cursor: pointer;
}
```
