### ISSUE TITLE
responisve.css from core breaks map

### ISSUE THREAD

**Issue by Paddy0174** [delahaye/dlh_googlemaps#72]
In the responsive.css from the core, there is an image setting  
```css
img {
    max-width:100%;
    height:auto;
}
```
that leads to a grey map (means no map at all, just a grey background).

As mentioned in this ticket from the contao core:
https://github.com/contao/core/issues/8651

Solution would be, to reset this setting in a css-file from dlh_googlemaps, after the responsive.css from the core is loaded
```css
img {
    max-width:none;
}
```
